server:
  port: 8888
  connection-timeout: 60000
mybatis:
  type-aliases-package: com.fest.watchtogether.entity
  mapper-locations: mapper/*Mapper.xml
spring:
  datasource:
    #    url: jdbc:mysql://39.108.184.215:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    username: root
  #  data:
  #    mongodb:
  #      uri: mongodb+srv://fest:7uxpe44x9bszxm5X@azure-hk-iluhu.azure.mongodb.net/test?retryWrites=true
  #        uri: mongodb://39.108.184.215:27017/test?retryWrites=true
  resources:
    static-locations: classpath:static/,file:static/,file:${custom.file.path}
  servlet:
    multipart:
      max-file-size: 64MB
      enabled: true
      max-request-size: 20480MB
logging:
  level:
    com.fest.watchtogether.dao: DEBUG
custom:
  file:
    path: E:/mvodResources/