server:
  port: 8888
mybatis:
  type-aliases-package: com.fest.watchtogether.entity
  mapper-locations: mapper/*Mapper.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    username: root
logging:
  level:
    com.fest.watchtogether.dao: DEBUG